<script setup lang="ts">
import { computed, onMounted, onDeactivated, onActivated, onBeforeUnmount, watch, reactive, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ElMessage } from "element-plus";
import FactoryAPI, { type ToolchainItem, type IntegrationConfig } from "@/api/module_factory";
import { useEmbeddedViewport, openService } from "@/api/module_factory/embedded";
import "@/api/module_factory/embedded.css";
const { panel, panelHeight } = useEmbeddedViewport();
const router = useRouter(); const route = useRoute();
const rows = ref<ToolchainItem[]>([]); const busy = ref(false); const onlyMissing = ref(false);
const drawer = ref(false); const selected = ref<IntegrationConfig>(); const draft = reactive<Record<string, any>>({});
let selection = 0;
let active = true;
const checking = ref(false); const result = ref<{status: string; message: string}>();
const shown = computed(() => rows.value.filter(x => !onlyMissing.value || !x.configured));
const count = computed(() => rows.value.filter(x => x.configured).length);
function error(e: any) { ElMessage.error(e?.response?.data?.msg || e?.response?.data?.detail || e?.message || "配置操作失败"); }
async function refresh() { busy.value = true; try { rows.value = await FactoryAPI.toolchain(); } catch(e) { error(e); } finally { busy.value = false; } }
async function configure(id: string) { const ticket = ++selection; busy.value = true; try { const value = await FactoryAPI.integrationConfig(id); if(ticket !== selection || !active) return; selected.value = value; for(const key of Object.keys(draft)) delete draft[key]; for(const f of selected.value.fields) draft[f.key] = f.value; draft.web_url = selected.value.web_url; result.value = undefined; drawer.value = true; } catch(e) { error(e); } finally { busy.value = false; } }
async function save() { if(!selected.value)return; busy.value = true; try { const values = {...draft}; for(const field of selected.value.fields) if(field.kind === "secret" && !values[field.key]) delete values[field.key]; selected.value = await FactoryAPI.saveIntegration(selected.value.id, selected.value.revision, values); for(const f of selected.value.fields) if(f.kind === "secret") draft[f.key] = ""; await refresh(); ElMessage.success("配置已保存，后续活动会读取；未部署的服务仍需部署"); } catch(e) { error(e); } finally { busy.value = false; } }
async function test() { if(!selected.value)return; checking.value = true; try { result.value = await FactoryAPI.probeIntegration(selected.value.id); } catch(e) { error(e); } finally { checking.value = false; } }
watch(drawer, open => { if(!open) for(const f of selected.value?.fields || []) if(f.kind === "secret") draft[f.key] = ""; });
onActivated(() => { active = true; });
onBeforeUnmount(() => { active = false; ++selection; });
onDeactivated(() => { active = false; ++selection; drawer.value = false; for(const key of Object.keys(draft)) delete draft[key]; });
onMounted(async () => { await refresh(); const tool = route.query.tool; if(active && typeof tool === "string" && rows.value.some(x => x.id === tool)) await configure(tool); });
</script>
<template>
  <div ref="panel" v-loading="busy" class="rnd-embedded" :style="{height: panelHeight}">
    <header class="rnd-toolbar"><div><h1>工具链配置 <el-tag effect="plain" size="small">{{ count }}/{{ rows.length }}</el-tag></h1><p>配置、部署、连通、任务回执分别记录</p></div><div class="rnd-actions"><el-checkbox v-model="onlyMissing">只看未配置</el-checkbox><el-button size="small" @click="refresh">刷新</el-button><el-button size="small" @click="router.push('/factory')">返回工作台</el-button></div></header>
    <div class="rnd-note">每个组件可进入配置。内置库已随镜像安装；外部服务与模型授权不会凭空创建，也不会把“填了地址”算成成功执行。</div>
    <div class="rnd-scroll"><div class="tool-grid"><article v-for="item in shown" :key="item.id" class="rnd-panel tool-card"><div class="tool-heading"><span class="tool-icon">{{ item.name.slice(0,2).toUpperCase() }}</span><strong>{{ item.name }}</strong><el-tag size="small" :type="item.configured ? 'info' : 'warning'">{{ item.configured ? '配置存在' : '待配置' }}</el-tag></div><p>{{ item.role }}</p><small class="rnd-muted">{{ item.execution }}</small><div class="tool-actions"><el-button size="small" type="primary" plain @click="configure(item.id)">配置 / 服务入口</el-button></div></article></div><el-empty v-if="!shown.length" :image-size="60" description="没有未配置的组件；实际运行仍需验证" /></div>
    <el-drawer v-model="drawer" :title="rows.find(x => x.id === selected?.id)?.name || '组件配置'" size="min(640px, 100vw)" append-to-body class="rnd-form"><template v-if="selected"><el-alert :title="selected.note" type="info" :closable="false" /><div class="rnd-actions" style="margin-bottom:16px"><el-button v-if="selected.web_url" @click="openService(selected.web_url)">打开服务管理页</el-button><el-button @click="openService(selected.docs)">官方文档</el-button><el-button v-if="selected.id === 'litellm'" type="primary" @click="drawer = false; router.push('/factory-providers')">配置模型与凭据</el-button><el-button v-if="selected.id === 'toolhive'" @click="configure('serena')">配置共享 MCP 端点</el-button></div><el-alert v-if="!selected.editable" title="当前账号可查看说明；修改全局设置需要超级管理员" type="warning" :closable="false" /><el-alert v-if="selected.requires_restart" title="Temporal 启动参数在 .env 中修改，重启 worker 后生效" type="warning" :closable="false" /><el-descriptions v-if="selected.requires_restart" :column="1" border size="small"><el-descriptions-item v-for="(value,key) in selected.startup_values" :key="key" :label="key">{{ value }}</el-descriptions-item></el-descriptions><el-form label-position="top" :disabled="!selected.editable"><el-form-item v-for="field in selected.fields" :key="field.key" :label="field.label + (field.kind === 'secret' && field.configured ? '（已保存，留空保留）' : '')"><el-switch v-if="field.kind === 'boolean'" v-model="draft[field.key]" /><el-input-number v-else-if="field.kind === 'number'" v-model="draft[field.key]" :min="field.minimum" :max="field.maximum" /><el-input v-else-if="field.kind === 'origins'" v-model="draft[field.key]" type="textarea" :rows="5" placeholder="https://models.example.com&#10;http://host.docker.internal:11434" /><el-input v-else v-model="draft[field.key]" :type="field.kind === 'secret' ? 'password' : 'text'" :show-password="field.kind === 'secret'" autocomplete="off" /><small class="rnd-muted">FACTORY_{{ field.key.toUpperCase() }}</small></el-form-item><el-form-item label="浏览器管理页（可与服务器连接 URL 不同）"><el-input v-model="draft.web_url" placeholder="https://… 或本站路由；没有独立服务界面可留空" /></el-form-item></el-form><p class="rnd-muted">加密保存到 PostgreSQL，覆盖环境默认值；不会改写 .env。不要在活动执行中更换服务或凭据。</p><el-alert v-if="result" :title="result.message" :type="result.status === 'failed' ? 'error' : result.status === 'requires_run' ? 'warning' : 'success'" :closable="false" /></template><template #footer><div class="rnd-actions"><el-button disabled title="旧恢复逻辑可能回退版本；请修改当前配置并保存">恢复默认</el-button><el-button :disabled="!selected?.editable" :loading="checking" @click="test">检查已保存配置</el-button><el-button type="primary" :disabled="!selected?.editable" :loading="busy" @click="save">保存配置</el-button></div></template></el-drawer>
  </div>
</template>
<style scoped>
.tool-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.tool-card{padding:14px;display:flex;flex-direction:column;gap:8px;min-width:0}.tool-heading{display:flex;gap:8px;align-items:flex-start;min-width:0}.tool-heading strong{font-size:13px;overflow-wrap:anywhere;flex:1;min-width:0}.tool-heading .el-tag{flex:none}.tool-icon{width:28px;height:28px;flex:none;font-size:10px;border-radius:7px;background:var(--el-color-primary-light-9);color:var(--el-color-primary);display:grid;place-items:center}.tool-card p{margin:0;font-size:12px;line-height:1.6;color:var(--el-text-color-regular);overflow-wrap:anywhere}.tool-actions{margin-top:auto;padding-top:4px}.tool-card small{overflow-wrap:anywhere}
@container(max-width:900px){.tool-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@container(max-width:520px){.tool-grid{grid-template-columns:minmax(0,1fr)}}
</style>
