"""Curated LiteLLM provider catalog for the workbench UI.

Mirrors the major chat providers that LiteLLM routes, with one-click base URLs
and popular model IDs so operators can configure gateways without memorizing
every endpoint. Local/self-hosted providers stay empty by default and must be
approved through FACTORY_MODEL_ALLOWED_ORIGINS.
"""
from __future__ import annotations

from typing import Any

# LiteLLM custom_llm_provider / model prefix for each catalog entry.
PROVIDER_PREFIX: dict[str, str] = {
    "openai": "openai",
    "anthropic": "anthropic",
    "azure_openai": "azure",
    "google": "gemini",
    "deepseek": "deepseek",
    "groq": "groq",
    "openrouter": "openrouter",
    "ollama": "ollama",
    "mistral": "mistral",
    "xai": "xai",
    "litellm_proxy": "openai",
    "custom_openai": "openai",
    "cerebras": "cerebras",
    "together_ai": "together_ai",
    "fireworks_ai": "fireworks_ai",
    "perplexity": "perplexity",
    "sambanova": "sambanova",
    "vertex_ai": "vertex_ai",
    "bedrock": "bedrock",
    "cohere": "cohere",
    "huggingface": "huggingface",
    "moonshot": "moonshot",
    "zai": "zai",
    "minimax": "minimax",
    "volcengine": "volcengine",
    "dashscope": "dashscope",
    "nvidia_nim": "nvidia_nim",
    "deepinfra": "deepinfra",
    "hyperbolic": "hyperbolic",
    "nebius": "nebius",
    "lambda": "lambda",
    "github": "github",
    "vllm": "openai",
    "lm_studio": "openai",
    "xinference": "openai",
    "wandb": "wandb",
    "watsonx": "watsonx",
    "scaleway": "scaleway",
    "cloudflare_workers": "cloudflare_workers",
    "aiml": "aiml",
    "novita": "novita",
    "nscale": "nscale",
    "xiaomi_mimo": "xiaomi_mimo",
    "siliconflow": "openai",
    "featherless": "featherless",
    "anyscale": "anyscale",
    "databricks": "databricks",
    "snowflake": "snowflake",
    "galadriel": "galadriel",
    "nano_gpt": "nano-gpt",
}

# Providers that may omit an API key (local / gateway / custom).
NO_KEY_PROVIDERS = frozenset({
    "ollama", "custom_openai", "litellm_proxy", "vllm", "lm_studio", "xinference",
})

# Providers that always need an explicit Base URL.
REQUIRE_BASE_URL = frozenset({
    "azure_openai", "litellm_proxy", "custom_openai", "ollama", "vllm",
    "lm_studio", "xinference",
})

# Providers known to accept OpenAI-style response_format json_object.
JSON_FORMAT_PROVIDERS = frozenset({
    "openai", "azure_openai", "deepseek", "groq", "openrouter", "xai",
    "litellm_proxy", "custom_openai", "mistral", "cerebras", "together_ai",
    "fireworks_ai", "deepinfra", "hyperbolic", "nebius", "moonshot", "zai",
    "minimax", "dashscope", "nvidia_nim", "github", "vllm", "lm_studio",
    "xinference", "siliconflow", "aiml", "novita", "nscale", "xiaomi_mimo",
    "featherless", "anyscale", "scaleway", "sambanova", "perplexity",
})

HOSTED_ORIGINS: dict[str, set[str]] = {
    "openai": {"https://api.openai.com"},
    "anthropic": {"https://api.anthropic.com"},
    "google": {"https://generativelanguage.googleapis.com"},
    "deepseek": {"https://api.deepseek.com"},
    "groq": {"https://api.groq.com"},
    "openrouter": {"https://openrouter.ai"},
    "mistral": {"https://api.mistral.ai"},
    "xai": {"https://api.x.ai"},
    "cerebras": {"https://api.cerebras.ai"},
    "together_ai": {"https://api.together.xyz"},
    "fireworks_ai": {"https://api.fireworks.ai"},
    "perplexity": {"https://api.perplexity.ai"},
    "sambanova": {"https://api.sambanova.ai"},
    "cohere": {"https://api.cohere.ai", "https://api.cohere.com"},
    "moonshot": {"https://api.moonshot.ai", "https://api.moonshot.cn"},
    "zai": {"https://api.z.ai", "https://open.bigmodel.cn"},
    "minimax": {"https://api.minimax.chat", "https://api.minimaxi.com"},
    "volcengine": {"https://ark.cn-beijing.volces.com"},
    "dashscope": {"https://dashscope.aliyuncs.com", "https://dashscope-intl.aliyuncs.com"},
    "nvidia_nim": {"https://integrate.api.nvidia.com"},
    "deepinfra": {"https://api.deepinfra.com"},
    "hyperbolic": {"https://api.hyperbolic.xyz"},
    "nebius": {"https://api.studio.nebius.ai"},
    "lambda": {"https://api.lambdalabs.com"},
    "github": {"https://models.inference.ai.azure.com", "https://api.githubcopilot.com"},
    "wandb": {"https://api.wandb.ai"},
    "scaleway": {"https://api.scaleway.com"},
    "cloudflare_workers": {"https://api.cloudflare.com"},
    "aiml": {"https://api.aimlapi.com"},
    "novita": {"https://api.novita.ai"},
    "nscale": {"https://inference.api.nscale.com"},
    "xiaomi_mimo": {"https://api.xiaomimimo.com", "https://api.mimo.xiaomi.com"},
    "featherless": {"https://api.featherless.ai"},
    "anyscale": {"https://api.endpoints.anyscale.com"},
    "galadriel": {"https://api.galadriel.com"},
    "nano_gpt": {"https://nano-gpt.com"},
}


def _models(*ids: str) -> list[dict[str, str]]:
    return [{"id": mid, "label": mid} for mid in ids]


# Catalog is intentionally explicit (not scraped) so the UI stays offline-safe
# and does not invent model IDs. Operators may always type a custom model ID.
PROVIDER_CATALOG: list[dict[str, Any]] = [
    {
        "id": "openai",
        "name": "OpenAI",
        "category": "主流云端",
        "description": "GPT / o-series，OpenAI 官方 API",
        "base_url": "",
        "default_base_url": "https://api.openai.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://platform.openai.com/docs",
        "models": _models("gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "gpt-4o", "gpt-4o-mini",
                           "o3", "o3-mini", "o4-mini", "gpt-5", "gpt-5-mini"),
    },
    {
        "id": "anthropic",
        "name": "Anthropic",
        "category": "主流云端",
        "description": "Claude 系列",
        "base_url": "",
        "default_base_url": "https://api.anthropic.com",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://docs.anthropic.com",
        "models": _models("claude-sonnet-4-5-20250929", "claude-sonnet-4-20250514",
                           "claude-3-7-sonnet-latest", "claude-3-5-haiku-latest",
                           "claude-opus-4-20250514", "claude-opus-4-1-20250805"),
    },
    {
        "id": "azure_openai",
        "name": "Azure OpenAI",
        "category": "主流云端",
        "description": "Azure 部署名 + api-version",
        "base_url": "",
        "default_base_url": "https://YOUR_RESOURCE.openai.azure.com",
        "requires_api_key": True,
        "requires_base_url": True,
        "supports_discover": False,
        "docs": "https://learn.microsoft.com/azure/ai-services/openai",
        "models": _models("gpt-4o", "gpt-4o-mini", "gpt-4.1", "gpt-4.1-mini"),
    },
    {
        "id": "google",
        "name": "Google Gemini",
        "category": "主流云端",
        "description": "Google AI Studio / Gemini API",
        "base_url": "",
        "default_base_url": "https://generativelanguage.googleapis.com",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://ai.google.dev",
        "models": _models("gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite",
                           "gemini-2.0-flash", "gemini-2.0-flash-lite"),
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "category": "主流云端",
        "description": "DeepSeek Chat / Reasoner",
        "base_url": "https://api.deepseek.com/v1",
        "default_base_url": "https://api.deepseek.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://api-docs.deepseek.com",
        "models": _models("deepseek-chat", "deepseek-reasoner"),
    },
    {
        "id": "groq",
        "name": "Groq",
        "category": "主流云端",
        "description": "高速开源模型推理",
        "base_url": "https://api.groq.com/openai/v1",
        "default_base_url": "https://api.groq.com/openai/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://console.groq.com/docs",
        "models": _models("llama-3.3-70b-versatile", "llama-3.1-8b-instant",
                           "openai/gpt-oss-120b", "openai/gpt-oss-20b",
                           "qwen/qwen3-32b", "moonshotai/kimi-k2-instruct"),
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "category": "聚合网关",
        "description": "一次接入数百个模型，保留厂商前缀",
        "base_url": "https://openrouter.ai/api/v1",
        "default_base_url": "https://openrouter.ai/api/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://openrouter.ai/docs",
        "models": _models(
            "anthropic/claude-sonnet-4", "openai/gpt-4.1", "openai/gpt-4.1-mini",
            "google/gemini-2.5-pro", "google/gemini-2.5-flash",
            "deepseek/deepseek-chat", "deepseek/deepseek-r1",
            "meta-llama/llama-3.3-70b-instruct", "x-ai/grok-3",
            "mistralai/mistral-large-latest", "qwen/qwen3-235b-a22b",
        ),
    },
    {
        "id": "litellm_proxy",
        "name": "LiteLLM Proxy",
        "category": "聚合网关",
        "description": "自建 LiteLLM 网关 / 模型别名",
        "base_url": "",
        "default_base_url": "http://litellm:4000/v1",
        "requires_api_key": False,
        "requires_base_url": True,
        "supports_discover": True,
        "docs": "https://docs.litellm.ai/docs/simple_proxy",
        "models": _models("factory-planner", "gpt-4o-mini", "claude-sonnet"),
    },
    {
        "id": "mistral",
        "name": "Mistral AI",
        "category": "主流云端",
        "description": "Mistral / Codestral",
        "base_url": "",
        "default_base_url": "https://api.mistral.ai/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.mistral.ai",
        "models": _models("mistral-large-latest", "mistral-medium-latest",
                           "mistral-small-latest", "codestral-latest", "open-mistral-nemo"),
    },
    {
        "id": "xai",
        "name": "xAI Grok",
        "category": "主流云端",
        "description": "Grok 系列",
        "base_url": "",
        "default_base_url": "https://api.x.ai/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.x.ai",
        "models": _models("grok-3", "grok-3-mini", "grok-4", "grok-code-fast-1"),
    },
    {
        "id": "cerebras",
        "name": "Cerebras",
        "category": "高速推理",
        "description": "超快开源模型推理",
        "base_url": "",
        "default_base_url": "https://api.cerebras.ai/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://inference-docs.cerebras.ai",
        "models": _models("llama3.1-8b", "llama-3.3-70b", "qwen-3-32b"),
    },
    {
        "id": "together_ai",
        "name": "Together AI",
        "category": "开源托管",
        "description": "大量开源模型托管",
        "base_url": "",
        "default_base_url": "https://api.together.xyz/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.together.ai",
        "models": _models("meta-llama/Llama-3.3-70B-Instruct-Turbo",
                           "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
                           "deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-72B-Instruct-Turbo"),
    },
    {
        "id": "fireworks_ai",
        "name": "Fireworks AI",
        "category": "开源托管",
        "description": "高速开源模型 API",
        "base_url": "",
        "default_base_url": "https://api.fireworks.ai/inference/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.fireworks.ai",
        "models": _models("accounts/fireworks/models/llama-v3p3-70b-instruct",
                           "accounts/fireworks/models/deepseek-v3",
                           "accounts/fireworks/models/qwen3-235b-a22b"),
    },
    {
        "id": "perplexity",
        "name": "Perplexity",
        "category": "检索增强",
        "description": "在线检索增强模型",
        "base_url": "",
        "default_base_url": "https://api.perplexity.ai",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://docs.perplexity.ai",
        "models": _models("sonar", "sonar-pro", "sonar-reasoning", "sonar-reasoning-pro"),
    },
    {
        "id": "sambanova",
        "name": "SambaNova",
        "category": "开源托管",
        "description": "SambaNova Cloud 推理",
        "base_url": "",
        "default_base_url": "https://api.sambanova.ai/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.sambanova.ai/cloud",
        "models": _models("Meta-Llama-3.3-70B-Instruct", "DeepSeek-V3-0324",
                           "QwQ-32B", "Llama-4-Maverick-17B-128E-Instruct"),
    },
    {
        "id": "moonshot",
        "name": "Moonshot Kimi",
        "category": "国内云端",
        "description": "月之暗面 Kimi API",
        "base_url": "",
        "default_base_url": "https://api.moonshot.ai/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://platform.moonshot.cn/docs",
        "models": _models("moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k",
                           "kimi-latest", "kimi-k2-0711-preview"),
    },
    {
        "id": "zai",
        "name": "智谱 Z.AI",
        "category": "国内云端",
        "description": "智谱 GLM / Z.AI",
        "base_url": "",
        "default_base_url": "https://api.z.ai/api/paas/v4",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://docs.z.ai",
        "models": _models("glm-4.5", "glm-4.5-air", "glm-4-plus", "glm-4-air",
                           "glm-4-flash", "glm-4.5-flash"),
    },
    {
        "id": "dashscope",
        "name": "阿里百炼 Qwen",
        "category": "国内云端",
        "description": "DashScope / 通义千问",
        "base_url": "",
        "default_base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://help.aliyun.com/zh/model-studio",
        "models": _models("qwen-max", "qwen-plus", "qwen-turbo", "qwen3-max",
                           "qwen3-coder-plus", "deepseek-v3", "deepseek-r1"),
    },
    {
        "id": "minimax",
        "name": "MiniMax",
        "category": "国内云端",
        "description": "MiniMax 大模型",
        "base_url": "",
        "default_base_url": "https://api.minimaxi.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://platform.minimaxi.com/document",
        "models": _models("MiniMax-Text-01", "abab6.5s-chat", "MiniMax-M1"),
    },
    {
        "id": "volcengine",
        "name": "火山方舟",
        "category": "国内云端",
        "description": "字节豆包 / 火山引擎 Ark",
        "base_url": "",
        "default_base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://www.volcengine.com/docs/82379",
        "models": _models("doubao-seed-1-6", "doubao-1-5-pro-32k", "doubao-1-5-lite-32k"),
    },
    {
        "id": "xiaomi_mimo",
        "name": "小米 MiMo",
        "category": "国内云端",
        "description": "小米 MiMo 开放平台",
        "base_url": "",
        "default_base_url": "https://api.xiaomimimo.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://platform.xiaomimimo.com/#/docs",
        "models": _models("mimo-v2.5", "mimo-v2.5-pro", "mimo-v2.5-flash"),
    },
    {
        "id": "siliconflow",
        "name": "硅基流动",
        "category": "国内云端",
        "description": "SiliconFlow 开源模型平台",
        "base_url": "https://api.siliconflow.cn/v1",
        "default_base_url": "https://api.siliconflow.cn/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.siliconflow.cn",
        "models": _models("Qwen/Qwen3-235B-A22B", "deepseek-ai/DeepSeek-V3",
                           "deepseek-ai/DeepSeek-R1", "THUDM/GLM-4-32B-0414",
                           "Pro/deepseek-ai/DeepSeek-V3"),
    },
    {
        "id": "deepinfra",
        "name": "DeepInfra",
        "category": "开源托管",
        "description": "低价开源模型推理",
        "base_url": "",
        "default_base_url": "https://api.deepinfra.com/v1/openai",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://deepinfra.com/docs",
        "models": _models("meta-llama/Llama-3.3-70B-Instruct",
                           "deepseek-ai/DeepSeek-V3", "Qwen/Qwen3-235B-A22B",
                           "openai/gpt-oss-120b"),
    },
    {
        "id": "hyperbolic",
        "name": "Hyperbolic",
        "category": "开源托管",
        "description": "Hyperbolic Labs 推理",
        "base_url": "",
        "default_base_url": "https://api.hyperbolic.xyz/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.hyperbolic.xyz",
        "models": _models("deepseek-ai/DeepSeek-V3", "Qwen/Qwen3-235B-A22B",
                           "meta-llama/Llama-3.3-70B-Instruct"),
    },
    {
        "id": "nebius",
        "name": "Nebius AI Studio",
        "category": "开源托管",
        "description": "Nebius 模型目录",
        "base_url": "",
        "default_base_url": "https://api.studio.nebius.ai/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.nebius.com/studio",
        "models": _models("meta-llama/Llama-3.3-70B-Instruct",
                           "deepseek-ai/DeepSeek-V3-0324", "Qwen/Qwen2.5-72B-Instruct"),
    },
    {
        "id": "nvidia_nim",
        "name": "NVIDIA NIM",
        "category": "开源托管",
        "description": "NVIDIA API Catalog / NIM",
        "base_url": "",
        "default_base_url": "https://integrate.api.nvidia.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.api.nvidia.com/nim",
        "models": _models("meta/llama-3.3-70b-instruct", "deepseek-ai/deepseek-r1",
                           "qwen/qwen3-235b-a22b"),
    },
    {
        "id": "github",
        "name": "GitHub Models",
        "category": "聚合网关",
        "description": "GitHub Models / Copilot 网关",
        "base_url": "",
        "default_base_url": "https://models.inference.ai.azure.com",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.github.com/en/github-models",
        "models": _models("gpt-4o", "gpt-4o-mini", "openai/gpt-4.1",
                           "anthropic/claude-sonnet-4", "deepseek/DeepSeek-V3-0324"),
    },
    {
        "id": "cloudflare_workers",
        "name": "Cloudflare Workers AI",
        "category": "边缘推理",
        "description": "Workers AI @cf 模型",
        "base_url": "",
        "default_base_url": "https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT/ai/v1",
        "requires_api_key": True,
        "requires_base_url": True,
        "supports_discover": False,
        "docs": "https://developers.cloudflare.com/workers-ai",
        "models": _models("@cf/meta/llama-3.3-70b-instruct-fp8-fast",
                           "@cf/qwen/qwen2.5-coder-32b-instruct"),
    },
    {
        "id": "aiml",
        "name": "AI/ML API",
        "category": "聚合网关",
        "description": "统一多模型网关",
        "base_url": "",
        "default_base_url": "https://api.aimlapi.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.aimlapi.com",
        "models": _models("gpt-4o", "claude-3-7-sonnet", "deepseek/deepseek-chat",
                           "google/gemini-2.5-flash"),
    },
    {
        "id": "novita",
        "name": "Novita AI",
        "category": "开源托管",
        "description": "Novita 模型 API",
        "base_url": "",
        "default_base_url": "https://api.novita.ai/v3/openai",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://novita.ai/docs",
        "models": _models("meta-llama/llama-3.3-70b-instruct",
                           "deepseek/deepseek_v3", "qwen/qwen3-235b-a22b"),
    },
    {
        "id": "nscale",
        "name": "Nscale",
        "category": "开源托管",
        "description": "欧盟主权推理",
        "base_url": "",
        "default_base_url": "https://inference.api.nscale.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://docs.nscale.com",
        "models": _models("meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3-0324"),
    },
    {
        "id": "featherless",
        "name": "Featherless AI",
        "category": "开源托管",
        "description": "无服务器开源模型",
        "base_url": "",
        "default_base_url": "https://api.featherless.ai/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.featherless.ai",
        "models": _models("meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3-0324"),
    },
    {
        "id": "scaleway",
        "name": "Scaleway",
        "category": "欧洲云端",
        "description": "Scaleway Generative APIs",
        "base_url": "",
        "default_base_url": "https://api.scaleway.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://www.scaleway.com/en/docs/ai-data/generative-apis",
        "models": _models("meta/llama-3.3-70b-instruct", "qwen/qwen3-235b-a22b",
                           "deepseek/deepseek-r1"),
    },
    {
        "id": "wandb",
        "name": "W&B Inference",
        "category": "实验平台",
        "description": "Weights & Biases Inference",
        "base_url": "",
        "default_base_url": "https://api.wandb.ai",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://weave-docs.wandb.ai/quickstart-inference",
        "models": _models("openai/gpt-oss-120b", "moonshotai/Kimi-K2-Instruct",
                           "deepseek/DeepSeek-V3-0324"),
    },
    {
        "id": "anyscale",
        "name": "Anyscale",
        "category": "开源托管",
        "description": "Anyscale Endpoints",
        "base_url": "",
        "default_base_url": "https://api.endpoints.anyscale.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://docs.anyscale.com/endpoints",
        "models": _models("meta-llama/Llama-3.3-70B-Instruct", "mistralai/Mixtral-8x7B-Instruct-v0.1"),
    },
    {
        "id": "galadriel",
        "name": "Galadriel",
        "category": "新兴云端",
        "description": "Galadriel LLM API",
        "base_url": "",
        "default_base_url": "https://api.galadriel.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://docs.galadriel.com",
        "models": _models("gpt-4o", "o3-mini"),
    },
    {
        "id": "nano_gpt",
        "name": "NanoGPT",
        "category": "聚合网关",
        "description": "Nano-GPT 多模型入口",
        "base_url": "",
        "default_base_url": "https://nano-gpt.com/api/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://nano-gpt.com/api",
        "models": _models("gpt-4o-mini", "claude-3-5-sonnet", "deepseek-chat"),
    },
    {
        "id": "lambda",
        "name": "Lambda AI",
        "category": "开源托管",
        "description": "Lambda 推理 API",
        "base_url": "",
        "default_base_url": "https://api.lambdalabs.com/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://docs.lambdalabs.com/inference",
        "models": _models("hermes3-405b", "llama3.3-70b-instruct", "deepseek-r1-671b"),
    },
    {
        "id": "databricks",
        "name": "Databricks",
        "category": "云平台",
        "description": "Databricks Foundation Models",
        "base_url": "",
        "default_base_url": "https://YOUR_WORKSPACE.cloud.databricks.com/serving-endpoints",
        "requires_api_key": True,
        "requires_base_url": True,
        "supports_discover": True,
        "docs": "https://docs.databricks.com/en/machine-learning/model-serving",
        "models": _models("databricks-meta-llama-3-1-70b-instruct", "databricks-claude-sonnet-4"),
        "extra_hint": "填写工作区 serving-endpoints 地址与 PAT token",
    },
    {
        "id": "snowflake",
        "name": "Snowflake Cortex",
        "category": "云平台",
        "description": "Cortex REST API",
        "base_url": "",
        "default_base_url": "",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://docs.snowflake.com/en/user-guide/snowflake-cortex",
        "models": _models("llama3.1-70b", "mistral-large2", "claude-3-5-sonnet"),
        "extra_hint": "依赖 Snowflake 账号鉴权；建议通过 LiteLLM Proxy 接入",
    },
    {
        "id": "watsonx",
        "name": "IBM watsonx",
        "category": "云平台",
        "description": "watsonx.ai Foundation Models",
        "base_url": "",
        "default_base_url": "https://us-south.ml.cloud.ibm.com",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://www.ibm.com/docs/en/watsonx",
        "models": _models("ibm/granite-3-8b-instruct", "meta-llama/llama-3-3-70b-instruct"),
        "extra_hint": "需要 project_id；复杂鉴权建议通过 LiteLLM Proxy",
    },
    {
        "id": "huggingface",
        "name": "Hugging Face",
        "category": "开源托管",
        "description": "HF Inference Providers",
        "base_url": "",
        "default_base_url": "https://api-inference.huggingface.co/v1",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": True,
        "docs": "https://huggingface.co/docs/api-inference",
        "models": _models("meta-llama/Llama-3.3-70B-Instruct", "Qwen/Qwen2.5-72B-Instruct",
                           "deepseek-ai/DeepSeek-V3"),
    },
    {
        "id": "cohere",
        "name": "Cohere",
        "category": "主流云端",
        "description": "Command R 系列",
        "base_url": "",
        "default_base_url": "https://api.cohere.com/v2",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://docs.cohere.com",
        "models": _models("command-r-plus", "command-r", "command-a"),
    },
    {
        "id": "vertex_ai",
        "name": "Google Vertex AI",
        "category": "云平台",
        "description": "GCP Vertex Gemini",
        "base_url": "",
        "default_base_url": "",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://cloud.google.com/vertex-ai",
        "models": _models("gemini-2.5-pro", "gemini-2.5-flash", "claude-sonnet-4@20250514"),
        "extra_hint": "需要 Vertex 凭据；复杂鉴权建议改用 google 或 litellm_proxy",
    },
    {
        "id": "bedrock",
        "name": "AWS Bedrock",
        "category": "云平台",
        "description": "Amazon Bedrock 托管模型",
        "base_url": "",
        "default_base_url": "",
        "requires_api_key": True,
        "requires_base_url": False,
        "supports_discover": False,
        "docs": "https://docs.aws.amazon.com/bedrock",
        "models": _models("anthropic.claude-3-5-sonnet-20240620-v1:0",
                           "anthropic.claude-3-haiku-20240307-v1:0",
                           "amazon.nova-pro-v1:0"),
        "extra_hint": "依赖 AWS 环境变量；生产建议通过 LiteLLM Proxy 统一出口",
    },
    {
        "id": "ollama",
        "name": "Ollama",
        "category": "本地部署",
        "description": "本地模型，默认 host.docker.internal:11434",
        "base_url": "http://host.docker.internal:11434",
        "default_base_url": "http://host.docker.internal:11434",
        "requires_api_key": False,
        "requires_base_url": True,
        "supports_discover": True,
        "docs": "https://ollama.com/library",
        "models": _models("llama3.1", "llama3.2", "qwen2.5-coder", "deepseek-r1",
                           "mistral", "phi4", "gemma3", "qwen3"),
        "discover_path": "ollama",
    },
    {
        "id": "vllm",
        "name": "vLLM",
        "category": "本地部署",
        "description": "自托管 vLLM OpenAI 兼容服务",
        "base_url": "http://host.docker.internal:8000/v1",
        "default_base_url": "http://host.docker.internal:8000/v1",
        "requires_api_key": False,
        "requires_base_url": True,
        "supports_discover": True,
        "docs": "https://docs.vllm.ai",
        "models": _models("meta-llama/Llama-3.3-70B-Instruct", "Qwen/Qwen2.5-72B-Instruct"),
    },
    {
        "id": "lm_studio",
        "name": "LM Studio",
        "category": "本地部署",
        "description": "LM Studio 本地服务器",
        "base_url": "http://host.docker.internal:1234/v1",
        "default_base_url": "http://host.docker.internal:1234/v1",
        "requires_api_key": False,
        "requires_base_url": True,
        "supports_discover": True,
        "docs": "https://lmstudio.ai/docs/basics/server",
        "models": [],
    },
    {
        "id": "xinference",
        "name": "Xinference",
        "category": "本地部署",
        "description": "Xorbits Inference",
        "base_url": "http://host.docker.internal:9997/v1",
        "default_base_url": "http://host.docker.internal:9997/v1",
        "requires_api_key": False,
        "requires_base_url": True,
        "supports_discover": True,
        "docs": "https://inference.readthedocs.io",
        "models": [],
    },
    {
        "id": "custom_openai",
        "name": "自定义 OpenAI 兼容",
        "category": "自定义",
        "description": "任意 OpenAI-compatible 端点（需管理员批准 origin）",
        "base_url": "",
        "default_base_url": "https://your-gateway.example.com/v1",
        "requires_api_key": False,
        "requires_base_url": True,
        "supports_discover": True,
        "docs": "https://docs.litellm.ai/docs/providers/openai_compatible",
        "models": [],
    },
]

CATEGORY_ORDER = [
    "主流云端", "国内云端", "聚合网关", "开源托管", "高速推理",
    "检索增强", "边缘推理", "欧洲云端", "实验平台", "新兴云端",
    "云平台", "本地部署", "自定义",
]

PROVIDER_KINDS: tuple[str, ...] = tuple(item["id"] for item in PROVIDER_CATALOG)


def catalog_payload() -> dict[str, Any]:
    """Public catalog payload for the workbench UI (no secrets)."""
    by_category: dict[str, list[dict[str, Any]]] = {}
    for item in PROVIDER_CATALOG:
        entry = {
            "id": item["id"],
            "name": item["name"],
            "category": item["category"],
            "description": item["description"],
            "base_url": item.get("base_url") or "",
            "default_base_url": item.get("default_base_url") or "",
            "requires_api_key": item["requires_api_key"],
            "requires_base_url": item["requires_base_url"],
            "supports_discover": item["supports_discover"],
            "docs": item["docs"],
            "models": item["models"],
            "litellm_prefix": PROVIDER_PREFIX.get(item["id"], "openai"),
            "is_local": item["id"] in {"ollama", "vllm", "lm_studio", "xinference"},
            "extra_hint": item.get("extra_hint") or "",
            "discover_path": item.get("discover_path") or "openai",
        }
        by_category.setdefault(item["category"], []).append(entry)
    categories = [name for name in CATEGORY_ORDER if name in by_category]
    for name in by_category:
        if name not in categories:
            categories.append(name)
    return {
        "categories": categories,
        "providers": [item for name in categories for item in by_category[name]],
        "quick_start": [
            {"provider": "openai", "model": "gpt-4.1-mini", "name": "OpenAI GPT-4.1 mini"},
            {"provider": "anthropic", "model": "claude-sonnet-4-5-20250929", "name": "Claude Sonnet 4.5"},
            {"provider": "google", "model": "gemini-2.5-flash", "name": "Gemini 2.5 Flash"},
            {"provider": "deepseek", "model": "deepseek-chat", "name": "DeepSeek Chat"},
            {"provider": "groq", "model": "llama-3.3-70b-versatile", "name": "Groq Llama 3.3 70B"},
            {"provider": "openrouter", "model": "anthropic/claude-sonnet-4", "name": "OpenRouter Claude"},
            {"provider": "moonshot", "model": "kimi-latest", "name": "Kimi Latest"},
            {"provider": "zai", "model": "glm-4.5", "name": "智谱 GLM-4.5"},
            {"provider": "dashscope", "model": "qwen-plus", "name": "通义千问 Plus"},
            {"provider": "xiaomi_mimo", "model": "mimo-v2.5", "name": "小米 MiMo"},
            {"provider": "ollama", "model": "qwen2.5-coder", "name": "本机 Ollama"},
            {"provider": "litellm_proxy", "model": "factory-planner", "name": "自建 LiteLLM"},
        ],
    }
